version: '3'

services:
  php:
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - redis-master
    networks:
      - redis-migration

  redis-master:
    image: redis:alpine
    ports:
      - "6360:6379"
    networks:
      - redis-migration

  redis-slave:
    image: redis:alpine
    command: redis-server --slaveof redis-master 6379 --replica-read-only no
    ports:
      - "6361:6379"
    networks:
      - redis-migration

networks:
  redis-migration:
    name: redis-migration